# Generated by Django 3.1.3 on 2021-12-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20211201_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='course',
            field=models.ManyToManyField(to='onlinecourse.Course'),
        ),
    ]
