# Generated by Django 3.1.3 on 2021-12-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_choice_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='course',
        ),
    ]
